### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by hounsellal** [bgryszko/react-native-circular-slider#4]
When I follow the instructions on the example I get a red screen and:
undefined is not an object (evaluating 'RNFSManager.RNFSFileTypeRegular')

**Comment by bgryszko** [comment]
Did you run `react-native link react-native-svg` command after install? Can you give more details – stacktrace (screenshot eventually) and what platform are you running?

**Comment by KinanKazmi** [comment]
@hounsellal If you're on android, you have to build the project again, after installing.
`react-native run-android`
