### ISSUE TITLE
Finding it hard to move slider both on phone and in emulator

### ISSUE THREAD

**Issue by Andersos** [bgryszko/react-native-circular-slider#7]
I attached a gif to show what I am experiencing.
![test](https://cloud.githubusercontent.com/assets/288977/22820718/48eeeb78-ef78-11e6-98ae-58659a1d8753.gif)

**Comment by bgryszko** [comment]
Interesting. It's android? Does original example works without an issue?

**Comment by Andersos** [comment]
It is on iOS. Have not gotten to test on Android yet. I can try and run the original example.

**Comment by Andersos** [comment]
Running the orignal example by cloning it and running `react-native run-ios` produces this error:

** BUILD FAILED **


The following build commands failed:

	CompileC /Users/anders/dev/react-native-circular-slider/example/Bedtime/ios/build/Build/Intermediates/RNSVG.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/RNSVGRect.o Shapes/RNSVGRect.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/Bedtime.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Bedtime.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Trying to run it as instructed in the README With XCode produces this error:

![screen shot 2017-02-10 at 12 23 59](https://cloud.githubusercontent.com/assets/288977/22825168/d852a21a-ef8b-11e6-8922-9caa9fd8ad4d.png)


Version of react-native:
Bedtime anders$ react-native -v
react-native-cli: 2.0.1
react-native: 0.39.2

Will try and update version as well.

**Comment by seratonik** [comment]
Experiencing the same dragging issue on iOS in both Simulator and Device in my own project (it only seems to be picking up the Y axis of the drag, not the X):

react-native-cli: 1.2.0
react-native: 0.41.2

Regarding the previous comment, I believe the original example just needs its `react-native-svg` dependency updated to work.

**Comment by bgryszko** [comment]
Hopefully fixed in eab7975c8f0b92eeb403824df3bfefdea9c99f7c

**Comment by iskWang** [comment]
![circular](https://cloud.githubusercontent.com/assets/3337244/24279166/205c8536-1083-11e7-977e-146eb03dd7b4.gif)

Hi, I've similar issue but android work fine(a little delay) and original example doesn't working for me.

* By yarn.lock
* react-native 0.37
* react-native-svg 4.3.3
