### ISSUE TITLE
Feature Request: Change Color of Start/Stop circles

### ISSUE THREAD

**Issue by abeaclark** [bgryszko/react-native-circular-slider#8]
Thanks for this great component. 

I would love to have a prop to set the color of the start/stop circles. This way they don't have to be the same color as the background circle.

Happy to submit a PR if it would help

**Comment by bgryszko** [comment]
Hey @abeaclark. In fact you're able to "overwrite" current circle around icon by setting stopIcon/startIcon – if you wrap the icon with SVG <Circle /> element :) But I'm happy to accept PR with optional `bgHandleColor` if current behaviour will be preserved (fallback to bgCircleColor).
